# Generated by Django 5.1.1 on 2025-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
