ERROR_DETAILS = {
    "token_not_valid": "Token is invalid or your session has expired. Please log in again.",
    "email_missing": "Email is required",
    "email_phone_missing": "Email or Phone Number is required",
    "username_or_password_missing": "Username or Password is missing",
    "email_error": "Error occurred while sending email",
    "user_already_verified": "User already exists and is verified",
    "otp_missing": "otp is required",
    "cannot_update_data": "Cannot update the data of the {field}",
    "no_active_user": "No active user found",
    "invalid_otp_type": "Invalid value for otp_type parameter",
    "invalid_action": "Invalid value for action parameter",
    "user_id_type_missing": "user_id or user_type or both parameters are missing",
    "invalid_otp": "Invalid OTP",
    "invalid_choices": "Invalid choices provided for {attr}",
    "invalid_answer": "Invalid answer",
    "user_not_found": "User Not Found",
    "user_role_not_found": "User Role Not Found",
    "module_not_found": "Module Not Found",
    "module_composition_not_found": "Module Composition Not Found",
    "module_permission_not_found": "Module Permission Not Found",
    "action_not_allowed": "Action is not allowed for current user",
    "review_not_found": "Review not found",
    "update_timings_not_allowed": "Updating timings on the event is not allowed. Create Event Update object to modify"
    " time for single or all future occurrences.",
    "method_not_allowed": "Method Not Allowed",
    "invalid_slot_id": "Invalid slot",
    "invalid_name": "Invalid name provided",
    "provider_not_found": "Provider not found",
    "refresh_token_missing": "refresh_token is required parameter",
    "something_went_wrong": "Something went wrong. Please try again.",
    "status_not_allowed": "Status update not allowed due to missing required data or current status of the object",
    "invalid_password": "Invalid password",
    "not_allowed": "Not allowed",
    "email_or_password_missing": "Email or password is missing",
    "user_id_or_code_missing": "User ID or code is missing",
    "invalid_user_id": "Invalid user ID",
    "email_and_phone_number_missing": "Email and Phone number is missing",
    "invalid_username": "Invalid username",
    "invalid_credentials": "Invalid credentials",
    "no_active_user": "No active user found",
    "host_not_found": "The Host is not found.",
    "role_not_found": "The role is not found.",
    "user_detail_not_found": "The visitor details is not found.",
    "existing_mobile_number": "The user's mobile number is already exist.",
    "existing_employee_number": "The user's employee number is already exist",
    "screen_detail_not_found": "The screen detail is not found.",
    "module_detail_not_found": "The module detail is not found.",
    "role_detail_not_found": "The role detail is not found.",
    "req_param_missing_email": "Invalid email or password. Please try again.",
}
